wobo_dtc_webenv/urls.py
from django.contrib import admin
from django.urls import path
from django.conf import settings
from django.views.static import serve
from django.conf.urls.static import static

from mailing_machine.views import index, create_new_export, schedule_sessions

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', admin.site.urls),
    path('', index),
    path('export/', create_new_export),
    path('schedule/', schedule_sessions)
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mailing_machine/models.py
from django.db import models

from django.utils.translation import ugettext_lazy as _

# Create your models here.


class WoBoConnection(models.Model):
    company = models.ForeignKey(verbose_name=_('Company'), to='mailing_machine.WoBoCompany', on_delete=models.CASCADE)
    user = models.ForeignKey(verbose_name=_('Creator'), to='auth.User', on_delete=models.SET_NULL, null=True)
    file = models.FilePathField(verbose_name=_('Latest Export File'))
    date_created = models.DateTimeField(auto_now=True)
    file_update_date = models.DateTimeField(auto_now=True)
    
    
class WoBoCompany(models.Model):
    api_key = models.CharField(verbose_name=_('API Key'), max_length=75, primary_key=True)
    company_name = models.CharField(verbose_name=_('Company Name'), max_length=125, null=True, blank=True)
    
    def __str__(self):
        return '{}'.format(self.company_name)
    
    
class WoBoTeam(models.Model):
    id = models.AutoField(verbose_name=_('WoBo Team ID'), primary_key=True)
    team_name = models.CharField(verbose_name=_('Team Name'), max_length=125)
    company = models.ForeignKey(verbose_name=_('Company'), to=WoBoCompany, on_delete=models.CASCADE, null=True)
    parent_team = models.ForeignKey(verbose_name=_('Parent Team'), to='mailing_machine.WoBoTeam',
                                    on_delete=models.CASCADE, blank=True, null=True)
    manager = models.IntegerField(verbose_name=_('Team Manager'), null=True)
    sessionDate = models.DateField(verbose_name=_('Session Date'), null=True)
    preMailSent = models.BooleanField(verbose_name=_('Pre-session E-Mail sent'), default=False)
    postMailSent = models.BooleanField(verbose_name=_('Post-session E-Mail sent'), default=False)
    members = models.ManyToManyField(to='mailing_machine.WoBoTeamMember')
    
    def __str__(self):
        
        try:
            cn = self.company.company_name
        except AttributeError:
            cn = 'ERROR'
        
        return '{} - {}'.format(self.team_name, cn)
    
    
class WoBoTeamMember(models.Model):
    first_name = models.CharField(verbose_name=_('First Name'), max_length=125)
    last_name = models.CharField(verbose_name=_('Last Name'), max_length=125)
    email = models.EmailField(verbose_name=_('E-Mail'))
    teams = models.ManyToManyField(verbose_name=_('Teams'), to=WoBoTeam, related_name='teams')
    
    def __str__(self):
        return '{} {} - {}'.format(self.first_name, self.last_name, self.email)

mailing_machine/forms.py
from django.forms import ModelForm

from .models import *
        
        
class CreateWoBoCompany(ModelForm):
    
    class Meta:
        model = WoBoCompany
        fields = ['company_name', 'api_key']

mailing_machine/views.py
from django.shortcuts import render, HttpResponseRedirect, reverse
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.utils.translation import ugettext_lazy as _
from django.db import IntegrityError

from .models import *
from .forms import *
from .functions import *

from datetime import datetime
import os


# Create your views here.
def index(request):
    template = 'pages/index.html'
    
    return render(request=request, context={'': ''}, template_name=template)


@login_required()
def create_new_export(request):
    
    template = 'pages/create_wobo_output.html'
    context = dict()
    
    form = CreateWoBoCompany()
    context['companies'] = WoBoCompany.objects.all()
    context['exports'] = WoBoConnection.objects.filter(user=request.user)
    api_key = request.GET.get('api_key')
    
    if api_key:
        
        try:
            context['company'] = WoBoConnection.objects.get(company__api_key=api_key)
            context['company'].file = build_data_sheet(api_key=api_key)
            context['company'].file_update_date = datetime.now()
            context['company'].save()
            
        except WoBoConnection.DoesNotExist:
            wobo_connect = {
                'company': WoBoCompany.objects.get(api_key=api_key),
                'user': request.user,
                'date_created': datetime.now(),
                'file_update_date': datetime.now(),
                'file': build_data_sheet(api_key=api_key)
            }
    
            WoBoConnection.objects.get_or_create(**wobo_connect)
        except IntegrityError or AttributeError or TypeError:
            messages.error(request=request, message=_('Invalid API Key or non-existent key.'))

    if request.method == 'POST':
        form = CreateWoBoCompany(request.POST)
        
        if form.is_valid():
            form = form.save(commit=True)
            wobo_connect = {
                'company': form,
                'user': request.user,
                'date_created': datetime.now(),
                'file_update_date': datetime.now(),
                'file': build_data_sheet(api_key=form.api_key)
            }
            
            WoBoConnection.objects.get_or_create(**wobo_connect)
            
            form.save()
            
        else:
            messages.error(request=request, message=_('The form is invalid...'))

    context['form'] = form
    context['exports'] = WoBoConnection.objects.filter(user=request.user, company__api_key=api_key).order_by(
        '-date_created')
    
    return render(request=request, context=context, template_name=template)


def schedule_sessions(request):
    
    context = dict()
    api_key = None
    form = CreateWoBoCompany()
    context['form'] = form
    
    if request.method == 'POST':
        context['company'] = WoBoCompany.objects.get_or_create(api_key=api_key, company_name=request.POST.get('company_name'))
        api_key = request.POST.get('api_key')
        
    else:
        api_key = request.GET.get('api_key')
        try:
            context['company'] = WoBoCompany.objects.get(api_key=api_key)
        except WoBoCompany.DoesNotExist:
            pass
        
    if 'company' in context.keys():
        context['teams'] = get_teams(api_key=api_key)
        context['users'] = get_users(api_key=api_key)

    template = 'pages/schedule_sessions/overview.html'
    context['form'] = form
    context['companies'] = WoBoCompany.objects.all()
    context['org_chart'] = build_org_chart(api_key=api_key)
    
    return render(request=request, context=context, template_name=template)

mailing_machine/templates/pages/base.html
{% load i18n staticfiles %}

<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>{% block page-title %}{% endblock %} | Detecon USA</title>
  <link rel="icon" href="{% static 'images/Detecon_Favicon.jpg' %}"/>
  <!-- Compiled and minified CSS -->
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">
  <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">

</head>
<body>
  <nav class="blue darken-4" role="navigation">
    <div class="nav-wrapper container"><a id="logo-container" href="/" class="brand-logo">
      <img src="{% static 'images/Detecon_DT_Group_white.png' %}" height="40" style="margin-top: 12px;"/>
    </a>
      <ul class="right hide-on-med-and-down">
        <li><a href="/">Home</a></li>
        <li><a href="/export/">Export WoBo Data</a></li>
        <li><a href="/schedule/">Schedule Sessions</a></li>
        <li style="border-left: 1px solid white;">
          <a href="/admin/">
            {{ request.user.username }}
            <i class="material-icons right">account_circle</i>
          </a>
        </li>
      </ul>

      <ul id="nav-mobile" class="sidenav">
        <li><a href="{% url 'admin:login' %}">Admin</a></li>
      </ul>
      <a href="#" data-target="nav-mobile" class="sidenav-trigger"><i class="material-icons">menu</i></a>
    </div>
  </nav>

  <div class="body">
    {% block body %}{% endblock %}
  </div>

    <footer class="page-footer orange">
    <div class="container">
      <div class="row">
        <div class="col l6 s12">
          <h5 class="white-text">Company Bio</h5>
          <p class="grey-text text-lighten-4">We are a team of college students working on this project like it's our full time job. Any amount would help support and continue development on this project and is greatly appreciated.</p>


        </div>
        <div class="col l3 s12">
          <h5 class="white-text">Settings</h5>
          <ul>
            <li><a class="white-text" href="#!">Link 1</a></li>
            <li><a class="white-text" href="#!">Link 2</a></li>
            <li><a class="white-text" href="#!">Link 3</a></li>
            <li><a class="white-text" href="#!">Link 4</a></li>
          </ul>
        </div>
        <div class="col l3 s12">
          <h5 class="white-text">Connect</h5>
          <ul>
            <li><a class="white-text" href="#!">Link 1</a></li>
            <li><a class="white-text" href="#!">Link 2</a></li>
            <li><a class="white-text" href="#!">Link 3</a></li>
            <li><a class="white-text" href="#!">Link 4</a></li>
          </ul>
        </div>
      </div>
    </div>
    <div class="footer-copyright">
      <div class="container">
      Made by <a class="orange-text text-lighten-3" href="http://materializecss.com">Materialize</a>
      </div>
    </div>
  </footer>

  <!-- Compiled and minified JavaScript -->
  <script src="https://code.jquery.com/jquery-3.4.1.min.js" integrity="sha256-CSXorXvZcTkaix6Yvo6HppcZGetbYMGWSFlBw8HfCJo=" crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
  <script>
     $(document).ready(function(){
      $('.collapsible').collapsible();
      $('select').formSelect();
    });
  </script>

</body>
</html>

mailing_machine/templates/pages/create_wobo_output.html
{% extends 'pages/base.html' %}
{% load i18n %}

{% block page-title %}Fetch Data from WorkBoard{% endblock %}

{% block body %}
  <div class="container">
    <div class="section">

      <div class="row">
        <div class="s12">
          <h1 style="font-size: 1.5rem">{% trans 'Get started now' %}</h1>
          <p>Here you can create WoBo Excel exports to get an overview of what is going on at a certain client.</p>
        </div>
      </div>

      <div class="row center">
        <div class="col s12">
          <form class="form" method="get" action=".">
            <div class="input-field col s12">
              <label for="id_company">Select a company</label>
              <select id="id_company" name="api_key">
                <option disabled selected></option>
                {% for company in companies %}
                  <option value="{{ company.api_key }}">{{ company.company_name }}</option>
                {% endfor %}
              </select>
              <button type="submit" class="btn waves-effect waves-light"><i class="material-icons right">send</i> Export all data</button>
            </div>
          </form>
        </div>
      </div>
      <br/>
      <br/>
      <br/>
      <div class="row ">
        <div class="col s12">
          <ul class="collapsible">
            <li>
              <div class="collapsible-header"><i class="material-icons">filter_drama</i>Fetch a new company</div>
              <div class="collapsible-body">
                <form class="form-row center" method="post" action=".">
                  {% csrf_token %}
                  {% for field in form %}
                    <div class="input-field">
                      <label for="{{ field.id_for_label }}">{{ field.label }}</label>
                      {{ field }}
                    </div>
                  {% endfor %}

                  <div class="input-field">
                    <button type="submit" class="btn waves-effect waves-light">
                      Submit
                      <i class="material-icons right">send</i>
                    </button>
                  </div>

                </form>
              </div>
            </li>
          </ul>
        </div>
      </div>

      <div class="row">
        <div class="col s12">
          <table>
            <thead>
              <tr>
                <th>#</th>
                <th>Company</th>
                <th>Date</th>
                <th>Author</th>
                <th>File</th>
              </tr>
            </thead>
            <tbody>
              {% for export in exports %}
                <tr>
                  <td>{{ forloop.counter }}</td>
                  <td>{{ export.company.company_name }}</td>
                  <td>{{ export.date_created }}</td>
                  <td>{{ export.user }}</td>
                  <td><a href="{{ export.file }}" download target="_blank">Download</a></td>
                </tr>
              {% endfor %}
            </tbody>
          </table>
        </div>
      </div>

    </div>
    <br><br>
  </div>

{% endblock %}

mailing_machine/templates/pages/index.html
{% extends 'pages/base.html' %}
{% load i18n staticfiles %}

{% block page-title %}Home{% endblock %}

{% block body %}

  <div class="section no-pad-bot" id="index-banner">
    <div class="container" style="min-height: 100vh;">
      <br><br>
      <h1 class="header center blue-text text-darken-3">Welcome to Detecon's OKR Rollout Management Tool</h1>
      <div class="row center">
        <h5 class="header col s12 light">Get started by signing in. Ask Yong if you don't have access yet.</h5>
      </div>
      <div class="row center">
        <a href="{% url 'admin:login' %}" id="download-button" class="btn-large waves-effect waves-light orange">Let's Go!</a>
      </div>
      <br><br>

    </div>
  </div>

{% endblock %}

mailing_machine/templates/pages/schedule_sessions/overview.html
{% extends 'pages/base.html' %}
{% load i18n %}

{% block page-title %}
  Manage Session Scheduling
{% endblock %}

{% block body %}
  <div class="container">
    <div class="section">

      <div class="row">
        <div class="s12">
          <h1 style="font-size: 1.4rem;">Let's schedule e-mails pre and post session.</h1>
        </div>
      </div>

      <div class="row">
        <div class="col s12">
          <p>{% for msg in messages %}{{ msg }}{% endfor %}</p>
          <p>{{ form.errors }}</p>
        </div>
      </div>

      <div class="row center">
        <div class="col s12">
          <form class="form" method="get" action=".">
            <div class="input-field col s12">
              <label for="id_company">Select a company</label>
              <select id="id_company" name="api_key">
                <option disabled selected></option>
                {% for company in companies %}
                  <option value="{{ company.api_key }}">{{ company.company_name }}</option>
                {% endfor %}
              </select>
              <button type="submit" class="btn waves-effect waves-light"><i class="material-icons right">send</i> Export all data</button>
            </div>
          </form>
        </div>
      </div>
      <br/>
      <br/>
      <div class="row ">
        <div class="col s12">
          <ul class="collapsible">
            <li>
              <div class="collapsible-header"><i class="material-icons">filter_drama</i>Fetch a new company</div>
              <div class="collapsible-body">
                <form class="form-row center" method="post" action=".">
                  {% csrf_token %}
                  {% for field in form %}
                    <div class="input-field">
                      <label for="{{ field.id_for_label }}">{{ field.label }}</label>
                      {{ field }}
                    </div>
                  {% endfor %}

                  <div class="input-field">
                    <button type="submit" class="btn waves-effect waves-light">
                      Submit
                      <i class="material-icons right">send</i>
                    </button>
                  </div>

                </form>
              </div>
            </li>
          </ul>
        </div>
      </div>

      <div class="row">
        <div class="col s12">
          <table>
            <thead>
              <tr>
                <th>#</th>
                <th>Team ID</th>
                <th>Team Name</th>
                <th>Manager ID</th>
                <th>Team</th>
              </tr>
            </thead>

            <tbody>

              {% for team in teams %}
                <tr>
                  <td>{{ forloop.counter }}</td>
                  <td>{{ team.pk }}</td>
                  <td>{{ team.team_name }}</td>
                  <td>{{ team.manager }}</td>
                  <td>{% for member in team.members.all %}{{ member.first_name }} {{ member.last_name }}, {% empty %}No members{% endfor %}</td>
                  <td>
                    <div class="col s8">
                      <div class="file-field">
                        <label for="id_datepicker">Pick a session date</label>
                        <input type="text" class="datepicker" id="id_datepicker">
                      </div>
                    </div>
                    <div class="col s4">
                      <button class="blue darken-3 waves-effect waves-light btn-small suffix" type="submit">
                        <i class="material-icons right">send</i>
                      </button>
                    </div>
                  </td>
                </tr>
                  {% for child in team.list %}
                    <tr>
                      <td style="padding-left: 35px">{{ forloop.counter }}</td>
                      <td>{{ child.pk }}</td>
                      <td>{{ child.name }}</td>
                      <td>{{ child.manager }}</td>
                      <td>{% for member in child.teams.all %}{{ member.first_name }} {{ member.last_name }}, {% empty %}No members{% endfor %}</td>
                      <td>
                        <div class="col s8">
                          <div class="file-field">
                            <label for="id_datepicker">Pick a session date</label>
                            <input type="text" class="datepicker" id="id_datepicker">
                          </div>
                        </div>
                        <div class="col s4">
                          <button class="blue darken-3 waves-effect waves-light btn-small suffix" type="submit">
                            <i class="material-icons right">send</i>
                          </button>
                        </div>
                      </td>
                    </tr>
                  {% endfor %}
              {% endfor %}
            </tbody>
          </table>
          <p><b>Elements found: {{ teams|length }}</b></p>
        </div>
      </div>
    </div>
    <br><br>
  </div>

  <script>
    document.addEventListener('DOMContentLoaded', function() {
      var elems = document.querySelectorAll('.datepicker');
      var instances = M.Datepicker.init(elems, options);
    });
  </script>

{% endblock %}